#!/usr/bin/env node
const { spawn } = require('child_process');

const child = spawn('npm', ['run', 'start'], {
  stdio: 'inherit',
  shell: true
});

child.on('exit', (code) => {
  process.exit(code || 0);
});